apt_cache_valid_time: 3600
apt_package_state: present
docker_users:
  - ansibleadmin

service_name: matomo-stack
service_src_folder: "/opt/{{ service_name }}"
docker_compose_file: "{{ service_src_folder }}/docker-compose.yml"