admin_user: ansibleadmin

users:
  - name: "{{ admin_user }}"
    groups:
      - sudo
      - ansibleadmin
      - docker
    keys:
      - "{{ lookup('dotenv', 'GITHUB_USER_KEYS') }}" #replace this with your github profile, if keys have been added
      # - "{{ lookup('file', gh_public_key_path ) }}"