---
- name: Ensure requested groups are present
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users | sum(attribute='groups', start=[]) | list | unique }}"

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Setup users
  user:
    name: "{{ item.name }}"
    group: "{{ item.groups[0] }}"
    groups: "{{ item.groups | join(',') }}"
    state: present
    shell: /bin/bash
  with_items: "{{ users }}"

- name: Add admin_user to sudoers file
  lineinfile:
    path: /etc/sudoers.d/admin-users
    line: ' {{ admin_user }} ALL=(ALL) NOPASSWD: ALL'
    # line: ' {{ admin_user }} ALL=(root) NOPASSWD: ALL'
    state: present
    mode: '0440'
    create: yes

- name: Add user SSH keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users | default([]) }}"
    - keys
  notify: restart ssh

- name: Add PubkeyAcceptedKeyTypes to sshd_config
  lineinfile:
    path: "/etc/ssh/sshd_config"
    line: "PubkeyAcceptedKeyTypes ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512"
    state: present
  notify: restart sshd