- name: Create Systemd service file for Docker Compose application
  ansible.builtin.template:
    src: templates/docker-compose-app.service.j2
    dest: /etc/systemd/system/docker-compose-app.service
    owner: root
    group: root
    mode: 0644
  notify: restart docker-compose-app

- name: Enable and start the Docker Compose application service
  ansible.builtin.systemd:
    name: docker-compose-app
    enabled: yes
    daemon_reload: yes
